name: chall2026-entity-crisis

services:
  entity-crisis:
    image: athack-ctf/chall2026-entity-crisis:latest
    container_name: chall2026-entity-crisis
    build:
      context: ./source
      dockerfile: Dockerfile
    ports:
      - "53006:8000"